Add dcos-autoscaler package
mesosphere/universe pull request #1030
Opened 2017-03-17 16:28 UTC by Ahmadposten

Adding package dcos-autoscaler to universe.

This package provides service autoscaling based on cpu or memory. Every app autoscaling behavior is configurable using labels similar to how marathon load balancer works.

2017-04-23 09:59 UTC, Ahmadposten commented
@jeorg84 can you please take a look at this?

2017-04-29 10:35 UTC, Ahmadposten commented
@ryadav88

2017-05-15 02:09 UTC, ryadav88 requested changes
Please add an example documentation by creating a PR against the https://github.com/dcos/examples repo. See other examples there for reference. This is also now a requirement for submitting packages to Universe.

2017-05-15 02:09 UTC, ryadav88 commented on repo/packages/D/dcos-autoscaler/0/package.json
> +  "framework": true,
`framework` should be false

2017-05-15 02:09 UTC, ryadav88 commented on repo/packages/D/dcos-autoscaler/0/package.json
> +  "tags": ["autoscaling", "mesosphere", "dcos"],
`mesosphere` tag is reserved for packages developed by Mesosphere. Please remove it.

2017-05-15 02:09 UTC, ryadav88 commented on repo/packages/D/dcos-autoscaler/0/package.json
> +{
Add `preInstallNotes` and add this line at the beginning of `preInstallNotes`: ```This DC/OS Service is currently in preview. There may be bugs, incomplete features, incorrect documentation, or other discrepancies. Preview packages should never be used in production!```

2017-05-15 02:09 UTC, ryadav88 commented on repo/packages/D/dcos-autoscaler/0/package.json
> +  "description": "Adds autoscaling to your application based on cpu and memory metrics",
Add a detailed description of what the package does, what it be used for.

2017-05-15 02:09 UTC, ryadav88 commented on repo/packages/D/dcos-autoscaler/0/package.json
> +{
Add a link to `dcos/examples` at the end of `preInstallNotes`

2017-05-15 02:09 UTC, ryadav88 commented on repo/packages/D/dcos-autoscaler/0/package.json
> +  "postInstallNotes": "Thank you for installing dcos autoscaler, Consult github.com/Ahmadposten/DC-OS-Marathon-autoscaling for more more info on usage and tuning configurations"
Add the `license` property.

2017-05-15 02:09 UTC, ryadav88 commented on repo/packages/D/dcos-autoscaler/0/resource.json
> +        "23b1cfe8e04a": "ahmadposten/dcos-autoscaler"
use a tagged version of the image

2017-05-28 18:41 UTC, Ahmadposten commented on repo/packages/D/dcos-autoscaler/0/package.json
> +{
@ryadav88  done .. please review again
here is the pull request for the examples repo https://github.com/dcos/examples/pull/170

2020-06-25 12:09 UTC, closed without merging