Ha configuration
mesosphere/universe pull request #1163
Opened 2017-05-10 22:37 UTC by skonto

Adds HA options.

2017-05-15 03:06 UTC, joerg84 commented
LGTM,
a) I still need to test this.
b) @ryadav88 this only adds new config options, would you still prefer a new package version for this?

2017-05-15 03:11 UTC, ryadav88 commented
@skonto @joerg84 yes, please update the package version and also bump the subdirectory version to 2.

2017-05-16 11:44 UTC, skonto commented
@ryadav88 I thought so I will update it accordingly, thnx.

2017-05-23 08:28 UTC, skonto commented
@ryadav88 @joerg84  I moved it to a new subdir, current version of the package is `1.2.0-1.4`. If I update that then docker image names need update as well since it depends on it. Should I update everything and then you push both images and code? Let me know how to proceed pls.

2017-06-05 02:31 UTC, ryadav88 commented
@skonto Yes, I would suggest updating the image too. Also, the default install of the package doesnt work. Please review the dcos example here and create a PR to reflect any changes https://github.com/dcos/examples/tree/master/flink

2017-06-09 13:19 UTC, skonto commented
@ryadav88 what do you mean by 

>  Also, the default install of the package doesnt work.

I have tested with a flink could you point me to issues or logs?

2017-06-14 17:19 UTC, skonto commented
WIP

2017-06-30 13:51 UTC, skonto commented
@joerg84 @ryadav88 | will put HA in 3 version. Sorry for the delay updating this.

2017-07-18 23:15 UTC, OhRobin commented
Default installation worked for me, but launching a job via the CLI does not work. Seems to be an issue with the jobmanager host being `localhost`

2017-07-20 17:26 UTC, EronWright requested changes

2017-07-20 17:26 UTC, EronWright commented on repo/packages/F/flink/2/config.json
> +    "high-availability": {
If possible, the defaults should support a side-by-side installation of numerous instances of the package.    We should use the service name as a component of the various ZK/HDFS paths and as the `cluster-id`.  I'm worried that users will get into serious trouble, with multiple Flink clusters interfering with each other.

2017-07-20 17:26 UTC, EronWright commented on repo/packages/F/flink/2/config.json
> +          "default":true,
I agree that HA should be enabled by default, iff we fix the side-by-side install issue.

2017-08-01 07:47 UTC, skonto commented
@OhRobin you need to use the jobmanager's correct ip... Is the comment referring to this PR?

2017-08-01 07:51 UTC, skonto commented on repo/packages/F/flink/2/config.json
> +    "high-availability": {
This is how people install different versions of the same package. They use a different service name. Ok will fix/check config options to comply with that.

2017-08-01 07:51 UTC, skonto commented on repo/packages/F/flink/2/config.json
> +          "default":true,
:+1:

2017-08-01 14:47 UTC, skonto commented
@EronWright @joerg84  I updated the PR. Will test and report back.

2017-08-02 12:08 UTC, skonto commented
Here is the guide how to run an example with the default settings:
https://gist.github.com/skonto/c8404d43142070dca860dda431459887
I will add an example to the example repos.

2017-08-02 12:59 UTC, skonto commented
https://github.com/dcos/examples/pull/196

2017-08-03 19:52 UTC, joerg84 commented
@skonto Thx, will check tomorrow!

2017-08-10 01:47 UTC, joerg84 commented
@skonto I will incorporate these changes in my universe PR for the Flink  release, ok?

2017-08-10 19:54 UTC, skonto commented
@joerg84 sure.

2017-08-20 20:37 UTC, skonto commented
@joerg84 should I update the PR?

2017-08-31 11:34 UTC, skonto commented
@ryadav88 what should I do with the PR? I am not sure if @joerg84 has merged with his work. Guys?

2017-08-31 14:19 UTC, ryadav88 commented
@joerg84 any update here?

2017-11-01 00:13 UTC, ryadav88 commented
Package updates have been merged since this. Closing the PR.

2017-11-01 00:13 UTC, closed without merging

2017-12-08 09:27 UTC, skonto commented
@ryadav88 I dont see HA merged somewhere? Why close this?

2017-12-11 04:52 UTC, ryadav88 commented
@skonto I can't remember now why I closed it then. @joerg84-  do you previous changes cover this? If not, we should reopen this PR. Let me know.

2018-02-26 22:19 UTC, skonto commented
@ryadav88 @joerg84 ?