Official NGINX image supported by NGINX, Inc.
mesosphere/universe pull request #1263
Opened 2017-07-03 22:27 UTC by cpretzer

We have created an official nginx image which will continue to maintain and support for the mesosphere universe.

2017-07-04 06:16 UTC, joerg84 commented
@cpretzer Just curious: is there a reason not to update the other nginx package with this image?

2017-07-05 18:31 UTC, cpretzer commented
@joerg84 the main reason was to preserve the version that the folks at bitnami created. We are happy to take that over, if they no longer want to support it.

2017-07-17 22:06 UTC, ryadav88 commented on repo/packages/N/nginx-official/0/package.json
> +  "minDcosReleaseVersion": "1.0.8",
should be 1.8.0

2017-07-18 04:27 UTC, ryadav88 requested changes
@cpretzer please review and update the example in github.com/dcos/examples

2017-07-18 04:27 UTC, ryadav88 commented on repo/packages/N/nginx-official/0/resource.json
> +        "nginx-docker": "nginx:latest"
use tagged version of a image.

2017-07-18 04:27 UTC, ryadav88 commented on repo/packages/N/nginx-official/0/package.json
> +  "name": "nginx-official",
change `name` to `nginx` and also update the subdirectory version to 7

2017-07-19 01:42 UTC, OhRobin commented
installation works with the example listed here https://github.com/dcos/examples/tree/master/nginx/1.9

2017-08-04 01:13 UTC, ryadav88 commented
@cpretzer any update here?

2017-08-04 04:29 UTC, cpretzer commented
@ryadav88, thanks for checking in. I'm planning to have this updated in the next few weeks.

2017-11-03 16:13 UTC, ryadav88 commented
@cpretzer any update here?

2018-03-10 18:14 UTC, ryadav88 commented
closing because of inactivity. Please reopen if youre still working on it.

2018-03-10 18:14 UTC, closed without merging