marathon 1.5.7 bump
mesosphere/universe pull request #1755
Opened 2018-03-22 19:37 UTC by meln1k

```
--- repo/packages/M/marathon/24/package.json	2018-03-22 20:31:04.000000000 +0100
+++ repo/packages/M/marathon/25/package.json	2018-03-22 20:32:27.000000000 +0100
@@ -1,8 +1,8 @@
 {
   "packagingVersion" : "3.0",
   "name" : "marathon",
-  "version" : "1.6.335",
-  "minDcosReleaseVersion" : "1.11",
+  "version" : "1.5.7",
+  "minDcosReleaseVersion" : "1.10",
   "scm" : "https://github.com/mesosphere/marathon.git",
   "maintainer" : "support@mesosphere.io",
   "description" : "A container orchestration platform for Mesos and DCOS.",
```
```
--- repo/packages/M/marathon/24/resource.json	2018-03-22 20:31:04.000000000 +0100
+++ repo/packages/M/marathon/25/resource.json	2018-03-22 20:34:39.000000000 +0100
@@ -7,7 +7,7 @@
   "assets": {
     "container": {
       "docker": {
-        "image": "mesosphere/marathon:v1.6.335"
+        "image": "mesosphere/marathon:v1.5.7"
       }
     }
   }
```

2018-03-22 19:41 UTC, kensipe requested changes
it looks like index `/24` is 1.6.322... 
in addition to this index /25 you will need to duplicate `/24` as `/26`.
This is so the default marathon for those on DCOS 1.11 will remain Marathon 1.6.332

2018-03-22 19:41 UTC, timcharper approved these changes

2018-03-22 20:07 UTC, kensipe approved these changes

2018-04-03 22:56 UTC, timcharper approved these changes

2018-04-05 16:42 UTC, merged