Confluent Components 4.0 Release With Security
mesosphere/universe pull request #1836
Opened 2018-05-02 18:16 UTC by cyan-confluent

2018-05-03 04:48 UTC, ryadav88 requested changes
The review comments apply to all the packages here.

2018-05-03 04:48 UTC, ryadav88 commented on repo/packages/C/confluent-connect/10/package.json
> +  "packagingVersion": "3.0",
change `packagingVersion` to 4.0

2018-05-03 04:48 UTC, ryadav88 commented on repo/packages/C/confluent-connect/10/package.json
> +  "preInstallNotes": "This DC/OS Service is currently in preview. Preparing to install confluent-connect",
you can remove this line: `This DC/OS Service is currently in preview.`

2018-05-03 04:48 UTC, ryadav88 commented on repo/packages/C/confluent-connect/10/package.json
> +  "minDcosReleaseVersion" : "1.10",
`minDcosReleaseVersion` should be 1.9

2018-05-04 21:38 UTC, cyan-confluent commented
@ryadav88 Your requested changes have been submitted.

2018-05-07 04:29 UTC, ryadav88 approved these changes

2018-05-07 04:29 UTC, merged