updated metadata
mesosphere/universe pull request #1838
Opened 2018-05-07 17:47 UTC by jmsprkr

Updated instana container version to reflect 1.0.5

2018-05-09 18:18 UTC, jmsprkr commented
Can I get some feedback on why these checks failed?

2018-05-14 19:41 UTC, ryadav88 requested changes

2018-05-14 19:41 UTC, ryadav88 commented on repo/packages/I/instana-agent/2/package.json
> +  "packagingVersion": "5.0",
change packagingVersion to 4.0

2018-05-14 19:41 UTC, ryadav88 commented on repo/packages/I/instana-agent/2/package.json
> +  "preInstallNotes": "This DC/OS Service is currently in preview. This package will deploy the Instana agent on your Mesos nodes.",
remove this line from `preInstallNotes` - `This DC/OS Service is currently in preview. `

2018-05-14 20:33 UTC, ryadav88 approved these changes

2018-05-14 20:33 UTC, merged