bump marathon 1.6.490
mesosphere/universe pull request #1871
Opened 2018-05-30 14:18 UTC by meln1k

2018-05-30 17:23 UTC, ichernetsky approved these changes

2018-05-31 14:19 UTC, kensipe requested changes
this is a bugging version for which @timcharper is working on a solution.  It needs to be updated with the fix or rolled back.

2018-06-04 10:17 UTC, meln1k commented
The bug is fixed in 1.6.490

2018-06-04 12:48 UTC, kensipe approved these changes

2018-06-04 15:14 UTC, timcharper approved these changes

2018-06-05 16:45 UTC, merged