Let's start with a simple mergebot integration.
mesosphere/universe pull request #1882
Opened 2018-06-16 03:05 UTC by orsenthil

Hey @joerg84  - we need to settle upon the labels for the repo..

* This file is the config for mergebot integration.
* It will apply "requested-changed" as soon as PR is created. I think, we need a different label. What label should it be?

2018-06-18 20:29 UTC, joerg84 commented
@orsenthil As discussed. How can I test this PR?

2018-06-25 21:36 UTC, orsenthil commented
@joerg84  - once we merge this PR, we give permissions to @mesosphere-mergebot-dev permissions to apply label and it will do something like this (This is test and proof: https://github.com/mesosphere-mergebot/mergebot-test-dcos/pull/144 ) For the config (https://github.com/mesosphere-mergebot/mergebot-test-dcos/blob/master/mergebot-config.json) that is same as the contents of this PR.

2018-06-29 00:51 UTC, joerg84 requested changes

2018-06-29 00:51 UTC, joerg84 commented on mergebot-config.json
> +    "default": "requested-changes"
This shouldn't be `requested-changes` see here: https://github.com/joerg84/universe/pull/2

2018-08-21 03:18 UTC, joerg84 approved these changes

2018-08-21 03:18 UTC, joerg84 commented
Thanks Team!

2018-08-21 03:23 UTC, merged