Release snaplogic-snaplex 4.14.0
mesosphere/universe pull request #1931
Opened 2018-08-01 20:40 UTC by VictorDu

Latest snaplogic-snaplex release

2018-08-03 17:38 UTC, joerg84 commented
Just started the CI, will take a look once done

2018-08-09 01:36 UTC, ryadav88 requested changes
Please also create a documentation example by submitting a PR to https://github.com/dcos/examples
You can use other examples there as a reference.

2018-08-09 01:36 UTC, ryadav88 commented on repo/packages/S/snaplogic-snaplex/0/package.json
> +    "packagingVersion": "2.0",
change to `4.0`

2018-08-09 01:36 UTC, ryadav88 commented on repo/packages/S/snaplogic-snaplex/0/package.json
> +    "postInstallNotes": "Snaplogic Snaplex has been installed.",
add `preInstall` notes

2018-08-09 01:36 UTC, ryadav88 commented on repo/packages/S/snaplogic-snaplex/0/package.json
> +    "postInstallNotes": "Snaplogic Snaplex has been installed.",
create a documentation example and add a link at the end of preInstallNotes

2018-08-09 01:36 UTC, ryadav88 commented on repo/packages/S/snaplogic-snaplex/0/package.json
> +    "version": "latest",
please use version of the format: integrationVersion-baseTechVersion. Ex: 0.1.0-1.2.3 if 1.2.3 is Snaplogic version

2018-08-09 01:36 UTC, ryadav88 commented on repo/packages/S/snaplogic-snaplex/0/package.json
> +    "description": "Snaplogic Snaplex",
add `license`

2018-08-09 01:36 UTC, ryadav88 commented on repo/packages/S/snaplogic-snaplex/0/resource.json
> +        "agent": "snaplogic/snaplex:latest"
use a tagged version of an image

2020-06-25 12:10 UTC, closed without merging